language: node_js
node_js: 14.16.0

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "alejozavala"
    token:
      secure: "f7147babd8f58dc59c4e7e829a8063d356388ba0"

notifications:
  slack: personalproje-ejg9749:38EcvtPJV2ddzGDUFTUPfbJ7

deploy:
  provider: heroku
  api_key: a3593154-7d88-44b5-9026-60bc9c48ee42
  app: insw-cicd
  on:
    branch: main