language: node_js
node_js: 14.16.0

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "alejozavala"
    token:
      secure: "f7147babd8f58dc59c4e7e829a8063d356388ba0"

notifications:
  slack: personalproje-ejg9749:38EcvtPJV2ddzGDUFTUPfbJ7